In [1]:
import pandas as pd
import numpy as np

In [3]:
isner = pd.read_csv('/Users/altairlanceaguelo/Desktop/COGS108Proj/Group053_SP25/isner_serve_chart.csv')
isner.drop(columns=['Unnamed: 0'], inplace=True)
isner = isner.replace('-', np.nan)

In [4]:
string_cols=[ 'Unret%', '<=3 W%',
       'RiP W%', 'RiP W%.1', 'SvImpact', '1st: Unret%', '1st: <=3 W%',
       'RiP W%.2', 'RiP W%.3', 'SvImpact1st', 'D Wide%', 'A Wide%', 'BP Wide%',
       '2nd: Unret%', '2nd: <=3 W%', '2nd: RiP W%']

for col in string_cols:
    isner[col] = isner[col].str.replace('%', '')
    isner[col] = isner[col].astype('float64')
isner

,year,tourney,round,result,opponent,Unret%,<=3 W%,RiP W%,RiP W%.1,SvImpact,...,RiP W%.2,RiP W%.3,SvImpact1st,D Wide%,A Wide%,BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2023,US Open,R64,L,Mmoh,48.1,63.0,55.7,64.3,55.6,...,55.7,64.3,73.1,57.1,40.3,0.0,19.6,34.8,45.9,69
1,2023,US Open,R128,W,Diaz,44.6,65.1,65.2,63.3,56.3,...,65.2,63.3,61.7,70.8,51.7,NaN,46.7,66.7,68.8,-79
2,2023,Houston,R16,L,Brouwer,50.9,66.7,60.0,69.2,58.2,...,60.0,69.2,72.5,53.8,52.6,0.0,45.5,59.1,50.0,103
3,2023,Dallas,F,L,Wu,64.4,71.2,41.5,32.0,67.0,...,41.5,32.0,75.4,40.0,48.1,50.0,42.9,53.6,56.3,-27
4,2023,Australian Open,R128,L,Mannarino,43.0,56.3,43.7,45.2,49.1,...,43.7,45.2,62.1,61.0,61.2,0.0,19.4,36.1,41.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,2011,Roland Garros,R128,L,Nadal,30.9,43.0,50.5,52.1,39.5,...,50.5,52.1,47.5,44.0,53.2,85.7,24.0,36.0,47.4,7
97,2010,Wimbledon,R128,W,Mahut,51.7,67.2,52.9,54.5,59.8,...,52.9,54.5,67.9,50.3,48.1,100.0,39.8,58.5,49.3,39
98,2010,Madrid,R16,L,Nadal,37.9,54.5,46.3,54.5,43.9,...,46.3,54.5,58.1,45.0,39.1,100.0,17.4,30.4,36.8,-79
99,2010,Australian Open,R16,L,Murray,20.7,33.3,42.4,54.1,31.8,...,42.4,54.1,50.4,55.2,61.5,100.0,0.0,0.0,22.7,-118
100,2009,US Open,R32,W,Roddick,38.7,57.1,60.2,63.8,47.7,...,60.2,63.8,59.2,50.0,50.0,60.0,30.0,50.0,54.3,107

In [5]:
isner.describe()

,year,Unret%,<=3 W%,RiP W%,RiP W%.1,SvImpact,1st: Unret%,1st: <=3 W%,RiP W%.2,RiP W%.3,SvImpact1st,D Wide%,A Wide%,BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,82.000000,101.000000,101.000000,101.000000,101.000000
mean,2017.465347,44.880198,58.700990,48.861386,51.572277,51.442574,54.178218,67.628713,48.861386,51.572277,63.683168,50.541584,46.469307,61.536585,25.584158,41.688119,44.783168,13.584158
std,3.559675,9.479104,9.626375,10.082777,12.341468,8.770557,10.686408,10.471011,10.082777,12.341468,9.679742,10.376842,10.185497,35.962341,11.805403,13.721234,13.919117,63.588248
min,2009.000000,20.700000,33.300000,20.000000,21.700000,30.200000,26.300000,36.800000,20.000000,21.700000,35.800000,28.600000,21.900000,0.000000,0.000000,0.000000,10.000000,-118.000000
25%,2015.000000,37.900000,53.800000,41.900000,44.400000,45.200000,47.000000,61.200000,41.900000,44.400000,58.000000,43.800000,39.600000,34.975000,16.700000,33.300000,35.700000,-25.000000
50%,2018.000000,44.600000,60.200000,47.800000,52.200000,51.200000,55.200000,69.000000,47.800000,52.200000,65.500000,51.500000,47.200000,66.700000,25.000000,43.500000,45.500000,7.000000
75%,2021.000000,52.100000,65.500000,56.400000,59.300000,57.200000,62.100000,75.400000,56.400000,59.300000,70.700000,58.300000,52.900000,100.000000,33.300000,51.400000,52.600000,56.000000
max,2023.000000,64.400000,76.100000,72.000000,78.300000,67.900000,73.100000,86.200000,72.000000,78.300000,80.500000,76.900000,70.800000,100.000000,53.600000,66.700000,80.000000,171.000000

In [6]:
isner[isner['tourney']=='Wimbledon']

,year,tourney,round,result,opponent,Unret%,<=3 W%,RiP W%,RiP W%.1,SvImpact,...,RiP W%.2,RiP W%.3,SvImpact1st,D Wide%,A Wide%,BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
10,2022,Wimbledon,R64,W,Murray,46.5,62.0,56.7,60.5,54.7,...,56.7,60.5,70.7,59.0,52.7,0.0,12.1,27.3,51.7,7
47,2018,Wimbledon,SF,L,Anderson,46.4,59.8,47.3,53.5,55.0,...,47.3,53.5,65.2,44.0,41.7,50.0,26.9,38.8,34.7,45
48,2018,Wimbledon,QF,W,Raonic,58.3,68.3,56.5,69.0,64.5,...,56.5,69.0,75.5,45.2,47.4,100.0,39.3,46.4,35.3,110
97,2010,Wimbledon,R128,W,Mahut,51.7,67.2,52.9,54.5,59.8,...,52.9,54.5,67.9,50.3,48.1,100.0,39.8,58.5,49.3,39

In [10]:
isner['tourney'].unique()

array(['US Open', 'Houston', 'Dallas', 'Australian Open', 'Paris',
       'Cincinnati', 'Newport', 'Wimbledon', 'Madrid', 'Indian Wells',
       'Canada', 'Atlanta', 'Acapulco', 'Roland Garros', 'Shanghai',
       'Beijing', 'Laver Cup', 'Washington', 'Miami', 'New York',
       'Tour Finals', 'Rome', 'Auckland', 'Basel', "Queen's Club", 'Nice',
       'London Olympics'], dtype=object)

In [34]:
surfaces = {'Wimbledon': 'grass',
           'Roland Garros': 'clay',
           'Doha': 'hard',
           'Australian Open': 'hard',
           'Tour Finals': 'hard',
           'Basel': 'hard',
           'Shanghai': 'hard',
           'Laver Cup': 'hard',
           'US Open': 'hard',
            'Cincinnati': 'hard',
           'Halle': 'grass',
           'Rome': 'clay',
           'Madrid': 'clay',
           'Miami': 'hard',
           'Indian Wells': 'hard',
           'Dubai': 'hard',
           'Paris': 'hard',
           'Stuttgart': 'grass',
           'Rotterdam': 'hard',
           'Canada': 'hard',
           'Monte': 'clay',
           'Brisbane': 'hard',
           'Istanbul': 'hard',
           'Davis': 'hard',
           'Hamburg': 'clay',
           'London Olympics': 'grass',
           'Stockholm': 'hard',
           'Masters': 'hard',
           'Beijing': 'hard',
           'Estoril': 'clay',
           'Tokyo': 'hard',
           'Bangkok': 'hard',
           'Gstaad': 'clay',
           'Vienna': 'hard',
           'Munich': 'clay',
           'Marseille': 'hard',
           'Milan': 'clay',
           'Sydney': 'hard',
           's': 'grass',
           'Houston': 'clay',
           'Dallas': 'hard',
           'Newport': 'grass',
           'Atlanta': 'hard',
           'Acapulco': 'hard',
           'Washington': 'hard',
           'New York': 'hard',
           'Auckland': 'hard',
           "Queen's Club": 'grass',
           'Nice': 'clay'}
isner['surface'] = isner['tourney'].apply(lambda x: surfaces[x])
isner

,year,tourney,round,result,opponent,Unret%,<=3 W%,RiP W%,RiP W%.1,SvImpact,...,RiP W%.3,SvImpact1st,D Wide%,A Wide%,BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg,surface
0,2023,US Open,R64,L,Mmoh,48.1,63.0,55.7,64.3,55.6,...,64.3,73.1,57.1,40.3,0.0,19.6,34.8,45.9,69,hard
1,2023,US Open,R128,W,Diaz,44.6,65.1,65.2,63.3,56.3,...,63.3,61.7,70.8,51.7,NaN,46.7,66.7,68.8,-79,hard
2,2023,Houston,R16,L,Brouwer,50.9,66.7,60.0,69.2,58.2,...,69.2,72.5,53.8,52.6,0.0,45.5,59.1,50.0,103,clay
3,2023,Dallas,F,L,Wu,64.4,71.2,41.5,32.0,67.0,...,32.0,75.4,40.0,48.1,50.0,42.9,53.6,56.3,-27,hard
4,2023,Australian Open,R128,L,Mannarino,43.0,56.3,43.7,45.2,49.1,...,45.2,62.1,61.0,61.2,0.0,19.4,36.1,41.4,1,hard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,2011,Roland Garros,R128,L,Nadal,30.9,43.0,50.5,52.1,39.5,...,52.1,47.5,44.0,53.2,85.7,24.0,36.0,47.4,7,clay
97,2010,Wimbledon,R128,W,Mahut,51.7,67.2,52.9,54.5,59.8,...,54.5,67.9,50.3,48.1,100.0,39.8,58.5,49.3,39,grass
98,2010,Madrid,R16,L,Nadal,37.9,54.5,46.3,54.5,43.9,...,54.5,58.1,45.0,39.1,100.0,17.4,30.4,36.8,-79,clay
99,2010,Australian Open,R16,L,Murray,20.7,33.3,42.4,54.1,31.8,...,54.1,50.4,55.2,61.5,100.0,0.0,0.0,22.7,-118,hard
100,2009,US Open,R32,W,Roddick,38.7,57.1,60.2,63.8,47.7,...,63.8,59.2,50.0,50.0,60.0,30.0,50.0,54.3,107,hard

In [33]:
isner_wpct = (isner['result'] == 'W').mean()
print(isner_wpct)

0.45544554455445546