In [1]:
import pandas as pd
import numpy as np

In [2]:
djo = pd.read_csv('../data/djokovic_serve_chart.csv')
djo = djo.replace('-', np.nan)
djo.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2025,Madrid,R64,L,Arnaldi,28.3%,35.8%,48.6%,33.4%,45.5%,54.5%,50.0%,53.6%,38.5%,45.0%,50.0%,0.0%,5.9%,47.1%,-118
1,2025,Monte Carlo,R32,L,Tabilo,14.3%,23.2%,50.0%,19.8%,23.3%,40.0%,56.5%,33.7%,56.3%,42.9%,25.0%,4.2%,4.2%,43.5%,-76
2,2025,Miami,F,L,Mensik,28.4%,41.9%,59.6%,35.9%,33.9%,51.8%,64.9%,43.9%,57.7%,66.7%,0.0%,11.8%,11.8%,46.7%,4
3,2025,Miami,SF,W,Dimitrov,33.3%,44.4%,62.1%,38.9%,35.9%,48.7%,68.0%,42.3%,42.1%,45.0%,0.0%,20.0%,20.0%,25.0%,65
4,2025,Miami,QF,W,Korda,47.5%,59.3%,61.3%,55.4%,53.1%,67.3%,65.2%,62.7%,42.9%,57.1%,NaN,20.0%,20.0%,50.0%,-79

In [3]:
djo.dtypes #show data types to see which cols to convert to numeric

year                  int64
tourney              object
round                object
result               object
opponent             object
overall: Unret%      object
overall: <=3 W%      object
overall: RiP W%      object
overall: SvImpact    object
1st: Unret%          object
1st: <=3 W%          object
1st: RiP W%          object
1st: SvImpact        object
1st: D Wide%         object
1st: A Wide%         object
1st: A BP Wide%      object
2nd: Unret%          object
2nd: <=3 W%          object
2nd: RiP W%          object
2ndAgg                int64
dtype: object

In [4]:
djo.columns

Index(['year', 'tourney', 'round', 'result', 'opponent', 'overall: Unret%',
       'overall: <=3 W%', 'overall: RiP W%', 'overall: SvImpact',
       '1st: Unret%', '1st: <=3 W%', '1st: RiP W%', '1st: SvImpact',
       '1st: D Wide%', '1st: A Wide%', '1st: A BP Wide%', '2nd: Unret%',
       '2nd: <=3 W%', '2nd: RiP W%', '2ndAgg'],
      dtype='object')

In [5]:
string_cols=[ 'overall: Unret%','overall: <=3 W%', 'overall: RiP W%',
             'overall: SvImpact','1st: Unret%', '1st: <=3 W%', 
             '1st: RiP W%', '1st: SvImpact','1st: D Wide%', '1st: A Wide%', 
             '1st: A BP Wide%', '2nd: Unret%','2nd: <=3 W%', '2nd: RiP W%']

for col in string_cols:
    djo[col] = djo[col].str.replace('%', '')
    djo[col] = djo[col].astype('float64')
djo.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2025,Madrid,R64,L,Arnaldi,28.3,35.8,48.6,33.4,45.5,54.5,50.0,53.6,38.5,45.0,50.0,0.0,5.9,47.1,-118
1,2025,Monte Carlo,R32,L,Tabilo,14.3,23.2,50.0,19.8,23.3,40.0,56.5,33.7,56.3,42.9,25.0,4.2,4.2,43.5,-76
2,2025,Miami,F,L,Mensik,28.4,41.9,59.6,35.9,33.9,51.8,64.9,43.9,57.7,66.7,0.0,11.8,11.8,46.7,4
3,2025,Miami,SF,W,Dimitrov,33.3,44.4,62.1,38.9,35.9,48.7,68.0,42.3,42.1,45.0,0.0,20.0,20.0,25.0,65
4,2025,Miami,QF,W,Korda,47.5,59.3,61.3,55.4,53.1,67.3,65.2,62.7,42.9,57.1,NaN,20.0,20.0,50.0,-79

In [6]:
djo['tourney'].unique()

array(['Madrid', 'Monte Carlo', 'Miami', 'Indian Wells', 'Doha',
       'Australian Open', 'Brisbane', 'Shanghai', 'US Open',
       'Paris Olympics', 'Wimbledon', 'Roland Garros', 'Geneva', 'Rome',
       'United Cup', 'Davis Cup', 'Tour Finals', 'Paris', 'Cincinnati',
       'Banja Luka', 'Dubai', 'Adelaide 1', 'Astana', 'Tel Aviv',
       'Laver Cup', 'Belgrade ', 'Tokyo Olympics', 'Belgrade 2',
       'Belgrade', 'Vienna', 'Atp Cup', 'Tokyo', 'Canada', "Queen's Club",
       'Eastbourne', 'Acapulco', 'Rio Olympics', 'Beijing',
       'London Olympics', 'Basel', 'Halle', 'Masters Cup', 'Bangkok',
       'Beijing Olympics', 'Hamburg', 'Estoril', 'Adelaide', 'Metz',
       'Amersfoort'], dtype=object)

In [7]:
surfaces = {'Wimbledon': 'grass',
           'Roland Garros': 'clay',
           'Doha': 'hard',
           'Australian Open': 'hard',
           'Tour Finals': 'hard',
           'Basel': 'hard',
           'Shanghai': 'hard',
           'Laver Cup': 'hard',
           'US Open': 'hard',
            'Cincinnati': 'hard',
           'Halle': 'grass',
           'Rome': 'clay',
           'Madrid': 'clay',
           'Miami': 'hard',
           'Indian Wells': 'hard',
           'Dubai': 'hard',
           'Paris': 'hard',
           'Stuttgart': 'grass',
           'Rotterdam': 'hard',
           'Canada': 'hard',
           'Monte Carlo': 'clay',
           'Brisbane': 'hard',
           'Istanbul': 'hard',
           'Davis Cup': 'hard',
           'Hamburg': 'clay',
           'London Olympics': 'grass',
           'Stockholm': 'hard',
           'Masters Cup': 'hard',
           'Beijing Olympics': 'hard',
           'Estoril': 'clay',
           'Tokyo': 'hard',
           'Bangkok': 'hard',
           'Gstaad': 'clay',
           'Vienna': 'hard',
           'Munich': 'clay',
           'Marseille': 'hard',
           'Milan': 'clay',
           'Sydney': 'hard',
           'Sydney Olympics': 'hard',
           's Hertogenbosch': 'grass',
           'Paris Olympics': 'clay',
           'Geneva': 'clay',
           'United Cup': 'hard',
           'Banja Luka': 'clay',
           'Adelaide 1': 'hard',
           'Astana': 'hard',
           'Tel Aviv': 'hard',
           'Belgrade ': 'hard',
           'Tokyo Olympics': 'hard',
           'Belgrade 2': 'hard',
           'Belgrade': 'hard',
           'Atp Cup': 'hard',
           'Queen\'s Club': 'grass',
           'Eastbourne': 'grass',
            'Acapulco': 'hard',
            'Rio Olympics': 'hard',
            'Beijing': 'hard',
            'Adelaide': 'hard',
            'Metz': 'hard',
            'Amersfoort': 'clay'}
djo['surface'] = djo['tourney'].apply(lambda x: surfaces[x])
djo.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,...,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg,surface
0,2025,Madrid,R64,L,Arnaldi,28.3,35.8,48.6,33.4,45.5,...,50.0,53.6,38.5,45.0,50.0,0.0,5.9,47.1,-118,clay
1,2025,Monte Carlo,R32,L,Tabilo,14.3,23.2,50.0,19.8,23.3,...,56.5,33.7,56.3,42.9,25.0,4.2,4.2,43.5,-76,clay
2,2025,Miami,F,L,Mensik,28.4,41.9,59.6,35.9,33.9,...,64.9,43.9,57.7,66.7,0.0,11.8,11.8,46.7,4,hard
3,2025,Miami,SF,W,Dimitrov,33.3,44.4,62.1,38.9,35.9,...,68.0,42.3,42.1,45.0,0.0,20.0,20.0,25.0,65,hard
4,2025,Miami,QF,W,Korda,47.5,59.3,61.3,55.4,53.1,...,65.2,62.7,42.9,57.1,NaN,20.0,20.0,50.0,-79,hard

In [8]:
djo = pd.get_dummies(djo, columns=['surface', 'result'])
djo.drop(columns=['result_L'], inplace=True)
#columns after one hot encoding
djo.columns

Index(['year', 'tourney', 'round', 'opponent', 'overall: Unret%',
       'overall: <=3 W%', 'overall: RiP W%', 'overall: SvImpact',
       '1st: Unret%', '1st: <=3 W%', '1st: RiP W%', '1st: SvImpact',
       '1st: D Wide%', '1st: A Wide%', '1st: A BP Wide%', '2nd: Unret%',
       '2nd: <=3 W%', '2nd: RiP W%', '2ndAgg', 'surface_clay', 'surface_grass',
       'surface_hard', 'result_W'],
      dtype='object')

In [9]:
djo.to_csv('../data/djokovic_serve_chart.csv', index=False)

In [10]:
djo.isna().sum() #show the number of missing values in each column

year                   0
tourney                0
round                  0
opponent               0
overall: Unret%        0
overall: <=3 W%        0
overall: RiP W%        0
overall: SvImpact      0
1st: Unret%            0
1st: <=3 W%            0
1st: RiP W%            0
1st: SvImpact          0
1st: D Wide%           0
1st: A Wide%           0
1st: A BP Wide%      106
2nd: Unret%            0
2nd: <=3 W%            0
2nd: RiP W%            0
2ndAgg                 0
surface_clay           0
surface_grass          0
surface_hard           0
result_W               0
dtype: int64

In [11]:
#use simple imputation to fill in missing values with the column mean
djo_imputed = djo.copy()
djo_imputed['1st: A BP Wide%'].fillna(djo_imputed['1st: A BP Wide%'].mean(), inplace=True)
djo_imputed.isna().sum() #show the number of missing values in each column after imputation

C:\Users\hslha\AppData\Local\Temp\ipykernel_19144\3382971566.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  djo_imputed['1st: A BP Wide%'].fillna(djo_imputed['1st: A BP Wide%'].mean(), inplace=True)

year                 0
tourney              0
round                0
opponent             0
overall: Unret%      0
overall: <=3 W%      0
overall: RiP W%      0
overall: SvImpact    0
1st: Unret%          0
1st: <=3 W%          0
1st: RiP W%          0
1st: SvImpact        0
1st: D Wide%         0
1st: A Wide%         0
1st: A BP Wide%      0
2nd: Unret%          0
2nd: <=3 W%          0
2nd: RiP W%          0
2ndAgg               0
surface_clay         0
surface_grass        0
surface_hard         0
result_W             0
dtype: int64

In [12]:
#save the imputed data
djo_imputed.to_csv('../data/djokovic_serve_chart_imputed.csv', index=False)

In [13]:
djo_speed = pd.read_csv('../data/djokovic_serve_speed.csv')
djo_speed.head()

,year,tourney,round,result,opponent,avg speed,1st: avg,1st: stdev,1st: t avg,1st: wide avg,1st: max,1st: min,2nd: avg,2nd: stdev,2nd: t avg,2nd: wide avg,2nd: max,2nd: min
0,2024,US Open,R32,L,Popyrin,108.0,114.9,6.3,117.7,112.9,124.0,94.0,94.8,9.5,104.6,86.0,117.0,77.0
1,2024,US Open,R64,W,Djere,106.0,117.9,4.9,118.3,116.0,125.0,105.0,93.2,10.0,103.6,97.6,119.0,78.0
2,2024,US Open,R128,W,Albot,107.5,116.6,6.6,119.9,110.8,126.0,104.0,96.7,11.0,94.8,101.2,117.0,78.0
3,2024,Wimbledon,F,L,Alcaraz,113.7,118.7,4.4,120.7,117.0,126.0,107.0,100.1,6.9,103.6,101.7,114.0,90.0
4,2024,Wimbledon,SF,W,Musetti,111.5,118.6,4.9,120.3,115.9,127.0,95.0,95.1,9.0,98.6,100.3,117.0,83.0

In [14]:
#one hot encoding for surface and result
djo_speed['surface'] = djo_speed['tourney'].apply(lambda x: surfaces[x])
djo_speed = pd.get_dummies(djo_speed, columns=['surface', 'result'])
djo_speed.drop(columns=['result_L'], inplace=True)
djo_speed.head()

,year,tourney,round,opponent,avg speed,1st: avg,1st: stdev,1st: t avg,1st: wide avg,1st: max,...,2nd: avg,2nd: stdev,2nd: t avg,2nd: wide avg,2nd: max,2nd: min,surface_clay,surface_grass,surface_hard,result_W
0,2024,US Open,R32,Popyrin,108.0,114.9,6.3,117.7,112.9,124.0,...,94.8,9.5,104.6,86.0,117.0,77.0,False,False,True,False
1,2024,US Open,R64,Djere,106.0,117.9,4.9,118.3,116.0,125.0,...,93.2,10.0,103.6,97.6,119.0,78.0,False,False,True,True
2,2024,US Open,R128,Albot,107.5,116.6,6.6,119.9,110.8,126.0,...,96.7,11.0,94.8,101.2,117.0,78.0,False,False,True,True
3,2024,Wimbledon,F,Alcaraz,113.7,118.7,4.4,120.7,117.0,126.0,...,100.1,6.9,103.6,101.7,114.0,90.0,False,True,False,False
4,2024,Wimbledon,SF,Musetti,111.5,118.6,4.9,120.3,115.9,127.0,...,95.1,9.0,98.6,100.3,117.0,83.0,False,True,False,True

In [15]:
djo_speed.to_csv('../data/djokovic_serve_speed.csv', index=False)

In [16]:
djo_speed.isnull().sum()

year               0
tourney            0
round              0
opponent           0
avg speed          0
1st: avg          58
1st: stdev        58
1st: t avg       145
1st: wide avg    145
1st: max           0
1st: min          58
2nd: avg          58
2nd: stdev        58
2nd: t avg       145
2nd: wide avg    146
2nd: max          58
2nd: min           0
surface_clay       0
surface_grass      0
surface_hard       0
result_W           0
dtype: int64

In [17]:
# use simple imputation to fill in missing values with the column mean
djo_speed_imputed = djo_speed.copy()
cols_to_impute = ['1st: avg','1st: stdev','1st: t avg','1st: wide avg','1st: min','2nd: avg','2nd: stdev',
                  '2nd: t avg','2nd: wide avg','2nd: max']
for col in cols_to_impute:
    djo_speed_imputed[col].fillna(djo_speed_imputed[col].mean(), inplace=True)
djo_speed_imputed.isna().sum() #show the number of missing values in each column after imputation

C:\Users\hslha\AppData\Local\Temp\ipykernel_19144\4061683141.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  djo_speed_imputed[col].fillna(djo_speed_imputed[col].mean(), inplace=True)

year             0
tourney          0
round            0
opponent         0
avg speed        0
1st: avg         0
1st: stdev       0
1st: t avg       0
1st: wide avg    0
1st: max         0
1st: min         0
2nd: avg         0
2nd: stdev       0
2nd: t avg       0
2nd: wide avg    0
2nd: max         0
2nd: min         0
surface_clay     0
surface_grass    0
surface_hard     0
result_W         0
dtype: int64

In [18]:
djo_speed_imputed.to_csv('../data/djokovic_serve_speed_imputed.csv', index=False)