In [9]:
import pandas as pd
import numpy as np

In [30]:
medvedev = pd.read_csv('../data/medvedev_serve_chart.csv')
medvedev = medvedev.replace('-', np.nan)
medvedev.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2025,Madrid,QF,L,Ruud,15.4%,33.3%,57.4%,26.3%,17.4%,41.3%,60.5%,35.9%,54.2%,77.3%,100.0%,14.8%,25.9%,52.2%,19
1,2025,Monte Carlo,R16,L,De,11.5%,13.5%,30.2%,13.7%,20.7%,24.1%,30.4%,24.5%,40.0%,21.4%,33.3%,0.0%,0.0%,30.0%,-118
2,2025,Miami,R64,L,Munar,18.9%,34.0%,48.7%,28.1%,22.6%,38.7%,50.0%,38.4%,75.0%,60.0%,100.0%,16.7%,33.3%,46.7%,32
3,2025,Indian Wells,SF,L,Rune,20.0%,26.7%,50.0%,24.5%,23.3%,33.3%,56.5%,32.3%,46.7%,20.0%,0.0%,16.7%,20.0%,44.0%,-79
4,2025,Indian Wells,QF,W,Fils,27.3%,34.1%,57.4%,30.1%,32.7%,41.8%,45.9%,37.3%,77.3%,54.5%,33.3%,20.0%,23.3%,75.0%,59

In [31]:
medvedev.dtypes #show data types to see which cols to convert to numeric

year                  int64
tourney              object
round                object
result               object
opponent             object
overall: Unret%      object
overall: <=3 W%      object
overall: RiP W%      object
overall: SvImpact    object
1st: Unret%          object
1st: <=3 W%          object
1st: RiP W%          object
1st: SvImpact        object
1st: D Wide%         object
1st: A Wide%         object
1st: A BP Wide%      object
2nd: Unret%          object
2nd: <=3 W%          object
2nd: RiP W%          object
2ndAgg                int64
dtype: object

In [32]:
medvedev.columns

Index(['year', 'tourney', 'round', 'result', 'opponent', 'overall: Unret%',
       'overall: <=3 W%', 'overall: RiP W%', 'overall: SvImpact',
       '1st: Unret%', '1st: <=3 W%', '1st: RiP W%', '1st: SvImpact',
       '1st: D Wide%', '1st: A Wide%', '1st: A BP Wide%', '2nd: Unret%',
       '2nd: <=3 W%', '2nd: RiP W%', '2ndAgg'],
      dtype='object')

In [33]:
string_cols=[ 'overall: Unret%','overall: <=3 W%', 'overall: RiP W%',
             'overall: SvImpact','1st: Unret%', '1st: <=3 W%', 
             '1st: RiP W%', '1st: SvImpact','1st: D Wide%', '1st: A Wide%', 
             '1st: A BP Wide%', '2nd: Unret%','2nd: <=3 W%', '2nd: RiP W%']

for col in string_cols:
    medvedev[col] = medvedev[col].str.replace('%', '')
    medvedev[col] = medvedev[col].astype('float64')
medvedev.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2025,Madrid,QF,L,Ruud,15.4,33.3,57.4,26.3,17.4,41.3,60.5,35.9,54.2,77.3,100.0,14.8,25.9,52.2,19
1,2025,Monte Carlo,R16,L,De,11.5,13.5,30.2,13.7,20.7,24.1,30.4,24.5,40.0,21.4,33.3,0.0,0.0,30.0,-118
2,2025,Miami,R64,L,Munar,18.9,34.0,48.7,28.1,22.6,38.7,50.0,38.4,75.0,60.0,100.0,16.7,33.3,46.7,32
3,2025,Indian Wells,SF,L,Rune,20.0,26.7,50.0,24.5,23.3,33.3,56.5,32.3,46.7,20.0,0.0,16.7,20.0,44.0,-79
4,2025,Indian Wells,QF,W,Fils,27.3,34.1,57.4,30.1,32.7,41.8,45.9,37.3,77.3,54.5,33.3,20.0,23.3,75.0,59

In [34]:
medvedev[medvedev['tourney'] == 'Stuttgart']

Empty DataFrame
Columns: [year, tourney, round, result, opponent, overall: Unret%, overall: <=3 W%, overall: RiP W%, overall: SvImpact, 1st: Unret%, 1st: <=3 W%, 1st: RiP W%, 1st: SvImpact, 1st: D Wide%, 1st: A Wide%, 1st: A BP Wide%, 2nd: Unret%, 2nd: <=3 W%, 2nd: RiP W%, 2ndAgg]
Index: []

In [60]:
surfaces = {'Miami': 'hard',
           'Indian Wells': 'hard',
           'Dubai': 'hard',
           'Australian Open': 'hard',
           'Auckland': 'hard',
           'Brisbane': 'hard',
           'Shanghai': 'hard',
           'Beijing': 'hard',
           'US Open': 'hard',
            'Cincinnati': 'hard',
           'Canada': 'hard',
           'Wimbledon': 'grass',
           'Roland Garros': 'clay',
           'Monte Carlo': 'clay',
           'Estoril': 'clay',
           'Doha': 'hard',
           'Stockholm': 'hard',
           'Madrid': 'clay',
           'Adelaide 1': 'hard',
           'Vienna': 'hard',
           'Sofia': 'hard',
           'Rotterdam': 'hard',
           'Montpellier': 'hard',
           'Paris': 'clay',
           'Antwerp': 'hard',
           'Kaohsiung CH': 'hard',
           'Eastbourne': 'grass',
           'Tour Finals': 'hard',
           'Tokyo': 'hard',
           'Washington': 'hard',
           'Davis Cup': 'clay',
           'Stuttgart': 'grass',
           'Marseille': 'hard',
           'Halle': 'grass',
           'Beijing Olympics': 'hard',
           'Rome': 'clay',
           'Paris Olympics': 'clay',
           's Hertogenbosch': 'grass',
           'Astana': 'hard',
           'Metz': 'hard',
           'Los Cabos': 'hard',
           'Acapulco': 'hard',
           'Atp Cup': 'hard',
           'Tokyo Olympics': 'hard',
           'Mallorca': 'grass',
           'St Petersburg': 'hard',
           'St. Petersburg': 'hard',
           "Queen's Club": 'grass',
           'Barcelona': 'clay',
           'Moscow': 'hard',
           'Winston-Salem': 'hard',
           'Sydney': 'hard',
           'Chennai': 'hard',
           'Orleans CH': 'hard',
           'Hamburg': 'clay',
           'Ilkley CH': 'grass',
           'Kazan CH': 'clay'}
medvedev['surface'] = medvedev['tourney'].apply(lambda x: surfaces[x])
medvedev.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,...,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg,surface
0,2025,Madrid,QF,L,Ruud,15.4,33.3,57.4,26.3,17.4,...,60.5,35.9,54.2,77.3,100.0,14.8,25.9,52.2,19,clay
1,2025,Monte Carlo,R16,L,De,11.5,13.5,30.2,13.7,20.7,...,30.4,24.5,40.0,21.4,33.3,0.0,0.0,30.0,-118,clay
2,2025,Miami,R64,L,Munar,18.9,34.0,48.7,28.1,22.6,...,50.0,38.4,75.0,60.0,100.0,16.7,33.3,46.7,32,hard
3,2025,Indian Wells,SF,L,Rune,20.0,26.7,50.0,24.5,23.3,...,56.5,32.3,46.7,20.0,0.0,16.7,20.0,44.0,-79,hard
4,2025,Indian Wells,QF,W,Fils,27.3,34.1,57.4,30.1,32.7,...,45.9,37.3,77.3,54.5,33.3,20.0,23.3,75.0,59,hard

In [61]:
medvedev = pd.get_dummies(medvedev, columns=['surface', 'result'])
medvedev.drop(columns=['result_L'], inplace=True)
#columns after one hot encoding
medvedev.columns

Index(['year', 'tourney', 'round', 'opponent', 'overall: Unret%',
       'overall: <=3 W%', 'overall: RiP W%', 'overall: SvImpact',
       '1st: Unret%', '1st: <=3 W%', '1st: RiP W%', '1st: SvImpact',
       '1st: D Wide%', '1st: A Wide%', '1st: A BP Wide%', '2nd: Unret%',
       '2nd: <=3 W%', '2nd: RiP W%', '2ndAgg', 'surface_clay', 'surface_grass',
       'surface_hard', 'result_W'],
      dtype='object')

In [64]:
medvedev.to_csv('../data/medvedev_serve_chart.csv', index=False)

In [65]:
medvedev.isna().sum() #show the number of missing values in each column

year                  0
tourney               0
round                 0
opponent              0
overall: Unret%       0
overall: <=3 W%       0
overall: RiP W%       0
overall: SvImpact     0
1st: Unret%           0
1st: <=3 W%           0
1st: RiP W%           0
1st: SvImpact         0
1st: D Wide%          0
1st: A Wide%          0
1st: A BP Wide%      57
2nd: Unret%           0
2nd: <=3 W%           0
2nd: RiP W%           0
2ndAgg                0
surface_clay          0
surface_grass         0
surface_hard          0
result_W              0
dtype: int64

In [66]:
#use simple imputation to fill in missing values with the column mean
medvedev_imputed = medvedev.copy()
medvedev_imputed['1st: A BP Wide%'].fillna(medvedev_imputed['1st: A BP Wide%'].mean(), inplace=True)
medvedev_imputed.isna().sum() #show the number of missing values in each column after imputation

C:\Users\Ashton\AppData\Local\Temp\ipykernel_18748\2129855819.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  medvedev_imputed['1st: A BP Wide%'].fillna(medvedev_imputed['1st: A BP Wide%'].mean(), inplace=True)

year                 0
tourney              0
round                0
opponent             0
overall: Unret%      0
overall: <=3 W%      0
overall: RiP W%      0
overall: SvImpact    0
1st: Unret%          0
1st: <=3 W%          0
1st: RiP W%          0
1st: SvImpact        0
1st: D Wide%         0
1st: A Wide%         0
1st: A BP Wide%      0
2nd: Unret%          0
2nd: <=3 W%          0
2nd: RiP W%          0
2ndAgg               0
surface_clay         0
surface_grass        0
surface_hard         0
result_W             0
dtype: int64

In [67]:
#save the imputed data
medvedev_imputed.to_csv('../data/medvedev_serve_chart_imputed.csv', index=False)

In [70]:
medvedev_speed = pd.read_csv('../data/medvedev_serve_speed.csv')
medvedev_speed.head()

,year,tourney,round,result,opponent,avg speed,1st: avg,1st: stdev,1st: t avg,1st: wide avg,1st: max,1st: min,2nd: avg,2nd: stdev,2nd: t avg,2nd: wide avg,2nd: max,2nd: min
0,2024,US Open,QF,L,Sinner,105.4,114.5,9.7,119.3,109.8,126.0,92.0,92.2,6.3,91.0,89.2,107.0,79.0
1,2024,US Open,R16,W,Borges,111.2,118.8,7.5,121.6,113.0,129.0,102.0,95.2,4.9,103.0,95.8,107.0,84.0
2,2024,US Open,R32,W,Cobolli,107.9,119.1,7.1,122.2,115.3,127.0,96.0,90.7,6.9,103.0,92.8,111.0,80.0
3,2024,US Open,R64,W,Marozsan,105.9,117.5,6.2,120.5,113.2,126.0,102.0,93.0,5.0,94.3,92.3,103.0,81.0
4,2024,US Open,R128,W,Lajovic,108.1,117.5,7.1,120.3,112.9,127.0,86.0,93.1,4.1,98.0,91.1,104.0,85.0

In [71]:
#one hot encoding for surface and result
medvedev_speed['surface'] = medvedev_speed['tourney'].apply(lambda x: surfaces[x])
medvedev_speed = pd.get_dummies(medvedev_speed, columns=['surface', 'result'])
medvedev_speed.drop(columns=['result_L'], inplace=True)
medvedev_speed.head()

,year,tourney,round,opponent,avg speed,1st: avg,1st: stdev,1st: t avg,1st: wide avg,1st: max,...,2nd: avg,2nd: stdev,2nd: t avg,2nd: wide avg,2nd: max,2nd: min,surface_clay,surface_grass,surface_hard,result_W
0,2024,US Open,QF,Sinner,105.4,114.5,9.7,119.3,109.8,126.0,...,92.2,6.3,91.0,89.2,107.0,79.0,False,False,True,False
1,2024,US Open,R16,Borges,111.2,118.8,7.5,121.6,113.0,129.0,...,95.2,4.9,103.0,95.8,107.0,84.0,False,False,True,True
2,2024,US Open,R32,Cobolli,107.9,119.1,7.1,122.2,115.3,127.0,...,90.7,6.9,103.0,92.8,111.0,80.0,False,False,True,True
3,2024,US Open,R64,Marozsan,105.9,117.5,6.2,120.5,113.2,126.0,...,93.0,5.0,94.3,92.3,103.0,81.0,False,False,True,True
4,2024,US Open,R128,Lajovic,108.1,117.5,7.1,120.3,112.9,127.0,...,93.1,4.1,98.0,91.1,104.0,85.0,False,False,True,True

In [72]:
# save the data
medvedev_speed.to_csv('../data/medvedev_serve_speed.csv', index=False)

In [73]:
medvedev_speed.isna().sum() #show the number of missing values in each column

year             0
tourney          0
round            0
opponent         0
avg speed        0
1st: avg         0
1st: stdev       0
1st: t avg       3
1st: wide avg    3
1st: max         0
1st: min         0
2nd: avg         0
2nd: stdev       0
2nd: t avg       5
2nd: wide avg    4
2nd: max         0
2nd: min         0
surface_clay     0
surface_grass    0
surface_hard     0
result_W         0
dtype: int64

In [75]:
# use simple imputation to fill in missing values with the column mean
medvedev_speed_imputed = medvedev_speed.copy()
cols_to_impute = ['1st: avg','1st: stdev','1st: t avg','1st: wide avg','1st: max','1st: min','2nd: avg','2nd: stdev',
                  '2nd: t avg','2nd: wide avg','2nd: max']
for col in cols_to_impute:
    medvedev_speed_imputed[col].fillna(medvedev_speed_imputed[col].mean(), inplace=True)
medvedev_speed_imputed.isna().sum() #show the number of missing values in each column after imputation

C:\Users\Ashton\AppData\Local\Temp\ipykernel_18748\2733679472.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  medvedev_speed_imputed[col].fillna(medvedev_speed_imputed[col].mean(), inplace=True)

year             0
tourney          0
round            0
opponent         0
avg speed        0
1st: avg         0
1st: stdev       0
1st: t avg       0
1st: wide avg    0
1st: max         0
1st: min         0
2nd: avg         0
2nd: stdev       0
2nd: t avg       0
2nd: wide avg    0
2nd: max         0
2nd: min         0
surface_clay     0
surface_grass    0
surface_hard     0
result_W         0
dtype: int64

In [76]:
#save the imputed data
medvedev_speed_imputed.to_csv('../data/medvedev_serve_speed_imputed.csv', index=False)