In [1]:
import pandas as pd
import numpy as np

In [3]:
monfils = pd.read_csv('../data/monfils_serve_chart.csv')
monfils = monfils.replace('-', np.NaN)
monfils.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2025,Miami,R32,W,Munar,24.5%,37.3%,60.3%,33.3%,32.9%,49.3%,67.3%,46.0%,45.7%,47.4%,0.0%,9.4%,15.6%,48.3%,-29
1,2025,Miami,R128,W,Marozsan,34.9%,50.6%,54.9%,41.7%,44.4%,63.0%,60.0%,54.8%,43.3%,58.3%,33.3%,19.2%,30.8%,47.6%,72
2,2025,Indian Wells,R32,L,Dimitrov,17.2%,27.0%,62.1%,22.9%,23.0%,35.1%,64.9%,32.3%,50.0%,47.2%,50.0%,9.5%,16.7%,57.9%,-26
3,2025,Dubai,R32,L,Berrettini,28.6%,39.7%,43.9%,33.5%,35.1%,48.6%,45.8%,43.5%,56.3%,57.1%,50.0%,22.7%,31.8%,41.2%,93
4,2025,Australian Open,R16,L,Shelton,24.2%,41.1%,63.5%,35.2%,36.5%,62.2%,72.3%,55.0%,42.9%,54.3%,33.3%,7.3%,12.2%,52.6%,-52

In [4]:
monfils.dtypes #show data types to see which cols to convert to numeric

year                  int64
tourney              object
round                object
result               object
opponent             object
overall: Unret%      object
overall: <=3 W%      object
overall: RiP W%      object
overall: SvImpact    object
1st: Unret%          object
1st: <=3 W%          object
1st: RiP W%          object
1st: SvImpact        object
1st: D Wide%         object
1st: A Wide%         object
1st: A BP Wide%      object
2nd: Unret%          object
2nd: <=3 W%          object
2nd: RiP W%          object
2ndAgg                int64
dtype: object

In [5]:
monfils.columns

Index(['year', 'tourney', 'round', 'result', 'opponent', 'overall: Unret%',
       'overall: <=3 W%', 'overall: RiP W%', 'overall: SvImpact',
       '1st: Unret%', '1st: <=3 W%', '1st: RiP W%', '1st: SvImpact',
       '1st: D Wide%', '1st: A Wide%', '1st: A BP Wide%', '2nd: Unret%',
       '2nd: <=3 W%', '2nd: RiP W%', '2ndAgg'],
      dtype='object')

In [6]:
string_cols=[ 'overall: Unret%','overall: <=3 W%', 'overall: RiP W%',
             'overall: SvImpact','1st: Unret%', '1st: <=3 W%', 
             '1st: RiP W%', '1st: SvImpact','1st: D Wide%', '1st: A Wide%', 
             '1st: A BP Wide%', '2nd: Unret%','2nd: <=3 W%', '2nd: RiP W%']

for col in string_cols:
    monfils[col] = monfils[col].str.replace('%', '')
    monfils[col] = monfils[col].astype('float64')
monfils.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2025,Miami,R32,W,Munar,24.5,37.3,60.3,33.3,32.9,49.3,67.3,46.0,45.7,47.4,0.0,9.4,15.6,48.3,-29
1,2025,Miami,R128,W,Marozsan,34.9,50.6,54.9,41.7,44.4,63.0,60.0,54.8,43.3,58.3,33.3,19.2,30.8,47.6,72
2,2025,Indian Wells,R32,L,Dimitrov,17.2,27.0,62.1,22.9,23.0,35.1,64.9,32.3,50.0,47.2,50.0,9.5,16.7,57.9,-26
3,2025,Dubai,R32,L,Berrettini,28.6,39.7,43.9,33.5,35.1,48.6,45.8,43.5,56.3,57.1,50.0,22.7,31.8,41.2,93
4,2025,Australian Open,R16,L,Shelton,24.2,41.1,63.5,35.2,36.5,62.2,72.3,55.0,42.9,54.3,33.3,7.3,12.2,52.6,-52

In [12]:
monfils[monfils['tourney'] == 'Stuttgart']

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
115,2015,Stuttgart,R16,W,Haider,35.5,51.3,59.0,43.0,50.0,68.8,58.3,61.9,37.5,40.6,0.0,16.7,33.3,60.0,1

In [14]:
surfaces = {'Miami': 'hard',
           'Indian Wells': 'hard',
           'Dubai': 'hard',
           'Australian Open': 'hard',
           'Auckland': 'hard',
           'Brisbane': 'hard',
           'Shanghai': 'hard',
           'Beijing': 'hard',
           'US Open': 'hard',
            'Cincinnati': 'hard',
           'Canada': 'hard',
           'Wimbledon': 'grass',
           'Roland Garros': 'clay',
           'Monte Carlo': 'clay',
           'Estoril': 'clay',
           'Doha': 'hard',
           'Stockholm': 'hard',
           'Madrid': 'clay',
           'Adelaide 1': 'hard',
           'Vienna': 'hard',
           'Sofia': 'hard',
           'Rotterdam': 'hard',
           'Montpellier': 'hard',
           'Paris': 'clay',
           'Antwerp': 'hard',
           'Kaohsiung CH': 'hard',
           'Eastbourne': 'grass',
           'Tour Finals': 'hard',
           'Tokyo': 'hard',
           'Washington': 'hard',
           'Davis Cup': 'clay',
           'Stuttgart': 'grass',
           'Marseille': 'hard',
           'Halle': 'grass',
           'Beijing Olympics': 'hard',
           'Rome': 'clay'}
monfils['surface'] = monfils['tourney'].apply(lambda x: surfaces[x])
monfils.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,...,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg,surface
0,2025,Miami,R32,W,Munar,24.5,37.3,60.3,33.3,32.9,...,67.3,46.0,45.7,47.4,0.0,9.4,15.6,48.3,-29,hard
1,2025,Miami,R128,W,Marozsan,34.9,50.6,54.9,41.7,44.4,...,60.0,54.8,43.3,58.3,33.3,19.2,30.8,47.6,72,hard
2,2025,Indian Wells,R32,L,Dimitrov,17.2,27.0,62.1,22.9,23.0,...,64.9,32.3,50.0,47.2,50.0,9.5,16.7,57.9,-26,hard
3,2025,Dubai,R32,L,Berrettini,28.6,39.7,43.9,33.5,35.1,...,45.8,43.5,56.3,57.1,50.0,22.7,31.8,41.2,93,hard
4,2025,Australian Open,R16,L,Shelton,24.2,41.1,63.5,35.2,36.5,...,72.3,55.0,42.9,54.3,33.3,7.3,12.2,52.6,-52,hard

In [15]:
monfils = pd.get_dummies(monfils, columns=['surface', 'result'])
monfils.drop(columns=['result_L'], inplace=True)
#columns after one hot encoding
monfils.columns

Index(['year', 'tourney', 'round', 'opponent', 'overall: Unret%',
       'overall: <=3 W%', 'overall: RiP W%', 'overall: SvImpact',
       '1st: Unret%', '1st: <=3 W%', '1st: RiP W%', '1st: SvImpact',
       '1st: D Wide%', '1st: A Wide%', '1st: A BP Wide%', '2nd: Unret%',
       '2nd: <=3 W%', '2nd: RiP W%', '2ndAgg', 'surface_clay', 'surface_grass',
       'surface_hard', 'result_W'],
      dtype='object')

In [16]:
monfils.to_csv('../data/monfils_serve_chart.csv', index=False)

In [17]:
monfils.isna().sum() #show the number of missing values in each column

year                  0
tourney               0
round                 0
opponent              0
overall: Unret%       0
overall: <=3 W%       0
overall: RiP W%       0
overall: SvImpact     0
1st: Unret%           0
1st: <=3 W%           0
1st: RiP W%           0
1st: SvImpact         0
1st: D Wide%          0
1st: A Wide%          0
1st: A BP Wide%      16
2nd: Unret%           0
2nd: <=3 W%           0
2nd: RiP W%           0
2ndAgg                0
surface_clay          0
surface_grass         0
surface_hard          0
result_W              0
dtype: int64

In [18]:
#use simple imputation to fill in missing values with the column mean
monfils_imputed = monfils.copy()
monfils_imputed['1st: A BP Wide%'].fillna(monfils_imputed['1st: A BP Wide%'].mean(), inplace=True)
monfils_imputed.isna().sum() #show the number of missing values in each column after imputation

/var/folders/2n/dlhg2h054cz7fjj9nq_spwtr0000gn/T/ipykernel_38818/3608047973.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  monfils_imputed['1st: A BP Wide%'].fillna(monfils_imputed['1st: A BP Wide%'].mean(), inplace=True)

year                 0
tourney              0
round                0
opponent             0
overall: Unret%      0
overall: <=3 W%      0
overall: RiP W%      0
overall: SvImpact    0
1st: Unret%          0
1st: <=3 W%          0
1st: RiP W%          0
1st: SvImpact        0
1st: D Wide%         0
1st: A Wide%         0
1st: A BP Wide%      0
2nd: Unret%          0
2nd: <=3 W%          0
2nd: RiP W%          0
2ndAgg               0
surface_clay         0
surface_grass        0
surface_hard         0
result_W             0
dtype: int64

In [ ]:
#save the imputed data
monfils_imputed.to_csv('../data/monfils_serve_chart_imputed.csv', index=False)

In [20]:
monfils_speed = pd.read_csv('../data/monfils_serve_speed.csv')
monfils_speed.head()

,year,tourney,round,result,opponent,avg speed,1st: avg,1st: stdev,1st: t avg,1st: wide avg,1st: max,1st: min,2nd: avg,2nd: stdev,2nd: t avg,2nd: wide avg,2nd: max,2nd: min
0,2024,US Open,R64,L,Ruud,107.7,115.5,11.2,116.8,110.5,133.0,94.0,97.7,7.1,101.5,101.7,116.0,85.0
1,2024,US Open,R128,W,Schwartzman,103.9,111.2,11.4,115.4,107.5,128.0,79.0,94.4,7.2,98.6,95.8,107.0,80.0
2,2024,Wimbledon,R32,L,Dimitrov,110.9,117.1,9.3,120.8,111.5,131.0,98.0,100.2,7.6,108.3,102.0,124.0,88.0
3,2024,Wimbledon,R64,W,Wawrinka,109.4,114.4,11.2,118.4,105.6,132.0,91.0,100.9,6.8,106.6,91.0,114.0,88.0
4,2024,Wimbledon,R128,W,Mannarino,107.4,113.5,9.4,117.1,109.9,129.0,93.0,96.2,7.3,93.7,97.0,119.0,82.0

In [21]:
#one hot encoding for surface and result
monfils_speed['surface'] = monfils_speed['tourney'].apply(lambda x: surfaces[x])
monfils_speed = pd.get_dummies(monfils_speed, columns=['surface', 'result'])
monfils_speed.drop(columns=['result_L'], inplace=True)
monfils_speed.head()

,year,tourney,round,opponent,avg speed,1st: avg,1st: stdev,1st: t avg,1st: wide avg,1st: max,...,2nd: avg,2nd: stdev,2nd: t avg,2nd: wide avg,2nd: max,2nd: min,surface_clay,surface_grass,surface_hard,result_W
0,2024,US Open,R64,Ruud,107.7,115.5,11.2,116.8,110.5,133.0,...,97.7,7.1,101.5,101.7,116.0,85.0,False,False,True,False
1,2024,US Open,R128,Schwartzman,103.9,111.2,11.4,115.4,107.5,128.0,...,94.4,7.2,98.6,95.8,107.0,80.0,False,False,True,True
2,2024,Wimbledon,R32,Dimitrov,110.9,117.1,9.3,120.8,111.5,131.0,...,100.2,7.6,108.3,102.0,124.0,88.0,False,True,False,False
3,2024,Wimbledon,R64,Wawrinka,109.4,114.4,11.2,118.4,105.6,132.0,...,100.9,6.8,106.6,91.0,114.0,88.0,False,True,False,True
4,2024,Wimbledon,R128,Mannarino,107.4,113.5,9.4,117.1,109.9,129.0,...,96.2,7.3,93.7,97.0,119.0,82.0,False,True,False,True

In [22]:
# save the data
monfils_speed.to_csv('../data/monfils_serve_speed.csv', index=False)

In [23]:
monfils_speed.isna().sum() #show the number of missing values in each column

year              0
tourney           0
round             0
opponent          0
avg speed         0
1st: avg         14
1st: stdev       14
1st: t avg       56
1st: wide avg    56
1st: max          0
1st: min         14
2nd: avg         14
2nd: stdev       14
2nd: t avg       58
2nd: wide avg    56
2nd: max         14
2nd: min          0
surface_clay      0
surface_grass     0
surface_hard      0
result_W          0
dtype: int64

In [24]:
# use simple imputation to fill in missing values with the column mean
monfils_speed_imputed = monfils_speed.copy()
cols_to_impute = ['1st: avg','1st: stdev','1st: t avg','1st: wide avg','1st: max','1st: min','2nd: avg','2nd: stdev',
                  '2nd: t avg','2nd: wide avg','2nd: max']
for col in cols_to_impute:
    monfils_speed_imputed[col].fillna(monfils_speed_imputed[col].mean(), inplace=True)
monfils_speed_imputed.isna().sum() #show the number of missing values in each column after imputation

/var/folders/2n/dlhg2h054cz7fjj9nq_spwtr0000gn/T/ipykernel_38818/2036105819.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  monfils_speed_imputed[col].fillna(monfils_speed_imputed[col].mean(), inplace=True)

year             0
tourney          0
round            0
opponent         0
avg speed        0
1st: avg         0
1st: stdev       0
1st: t avg       0
1st: wide avg    0
1st: max         0
1st: min         0
2nd: avg         0
2nd: stdev       0
2nd: t avg       0
2nd: wide avg    0
2nd: max         0
2nd: min         0
surface_clay     0
surface_grass    0
surface_hard     0
result_W         0
dtype: int64

In [25]:
#save the imputed data
monfils_imputed.to_csv('../data/monfils_serve_chart_imputed.csv', index=False)