In [1]:
import pandas as pd
import numpy as np

In [2]:
man = pd.read_csv('../data/schwartzman_serve_chart.csv')
man = man.replace('-', np.nan)
man.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2025,Buenos Aires,R16,L,Martinez,9.5%,19.0%,38.2%,16.0%,14.8%,25.9%,34.8%,24.8%,22.2%,38.9%,20.0%,0.0%,9.1%,45.5%,-118
1,2025,Buenos Aires,R32,W,Jarry,26.3%,35.1%,57.5%,31.4%,27.6%,38.2%,58.2%,35.3%,31.3%,47.7%,33.3%,26.5%,32.4%,56.0%,80
2,2024,US Open,R128,L,Monfils,11.3%,17.4%,47.0%,15.0%,16.2%,24.3%,43.5%,21.9%,54.3%,43.6%,33.3%,2.6%,5.1%,52.6%,-91
3,2023,Wimbledon,R64,L,Sinner,13.6%,17.3%,47.1%,17.7%,15.5%,20.7%,51.0%,21.2%,53.8%,15.6%,16.7%,9.5%,9.5%,36.8%,-22
4,2023,Barcelona,R64,W,Wu,23.8%,31.0%,59.4%,27.9%,25.0%,28.6%,47.6%,31.1%,60.0%,30.8%,NaN,21.4%,35.7%,81.8%,-79

In [3]:
man.dtypes #show data types to see which cols to convert to numeric

year                  int64
tourney              object
round                object
result               object
opponent             object
overall: Unret%      object
overall: <=3 W%      object
overall: RiP W%      object
overall: SvImpact    object
1st: Unret%          object
1st: <=3 W%          object
1st: RiP W%          object
1st: SvImpact        object
1st: D Wide%         object
1st: A Wide%         object
1st: A BP Wide%      object
2nd: Unret%          object
2nd: <=3 W%          object
2nd: RiP W%          object
2ndAgg                int64
dtype: object

In [4]:
man.columns

Index(['year', 'tourney', 'round', 'result', 'opponent', 'overall: Unret%',
       'overall: <=3 W%', 'overall: RiP W%', 'overall: SvImpact',
       '1st: Unret%', '1st: <=3 W%', '1st: RiP W%', '1st: SvImpact',
       '1st: D Wide%', '1st: A Wide%', '1st: A BP Wide%', '2nd: Unret%',
       '2nd: <=3 W%', '2nd: RiP W%', '2ndAgg'],
      dtype='object')

In [5]:
string_cols=[ 'overall: Unret%','overall: <=3 W%', 'overall: RiP W%',
             'overall: SvImpact','1st: Unret%', '1st: <=3 W%', 
             '1st: RiP W%', '1st: SvImpact','1st: D Wide%', '1st: A Wide%', 
             '1st: A BP Wide%', '2nd: Unret%','2nd: <=3 W%', '2nd: RiP W%']

for col in string_cols:
    man[col] = man[col].str.replace('%', '')
    man[col] = man[col].astype('float64')
man.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,1st: <=3 W%,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg
0,2025,Buenos Aires,R16,L,Martinez,9.5,19.0,38.2,16.0,14.8,25.9,34.8,24.8,22.2,38.9,20.0,0.0,9.1,45.5,-118
1,2025,Buenos Aires,R32,W,Jarry,26.3,35.1,57.5,31.4,27.6,38.2,58.2,35.3,31.3,47.7,33.3,26.5,32.4,56.0,80
2,2024,US Open,R128,L,Monfils,11.3,17.4,47.0,15.0,16.2,24.3,43.5,21.9,54.3,43.6,33.3,2.6,5.1,52.6,-91
3,2023,Wimbledon,R64,L,Sinner,13.6,17.3,47.1,17.7,15.5,20.7,51.0,21.2,53.8,15.6,16.7,9.5,9.5,36.8,-22
4,2023,Barcelona,R64,W,Wu,23.8,31.0,59.4,27.9,25.0,28.6,47.6,31.1,60.0,30.8,NaN,21.4,35.7,81.8,-79

In [6]:
man['tourney'].unique()

array(['Buenos Aires', 'US Open', 'Wimbledon', 'Barcelona', 'Monte Carlo',
       'Indian Wells', 'Australian Open', 'Paris', 'Hamburg',
       "Queen's Club", 'Madrid', 'Rio de Janeiro', 'Atp Cup', 'Vienna',
       'Antwerp', 'Davis Cup', 'Cincinnati', 'Roland Garros', 'Miami',
       'Cologne 2', 'Rome', 'Cordoba', 'Los Cabos', 'Munich', 'Acapulco',
       'Tokyo', 'Canada', 'Marrakech', 'Sao Paulo', 'Istanbul',
       'Montevideo CH', 'Guayaquil CH', 'Corrientes CH',
       'Potro Alegre CH', 'Campinas CH', 'Bastad'], dtype=object)

In [27]:
surfaces = {'Wimbledon': 'grass',
           'Roland Garros': 'clay',
           'Doha': 'hard',
           'Australian Open': 'hard',
           'Tour Finals': 'hard',
           'Basel': 'hard',
           'Shanghai': 'hard',
           'Laver Cup': 'hard',
           'US Open': 'hard',
           'Cincinnati': 'hard',
           'Halle': 'grass',
           'Rome': 'clay',
           'Madrid': 'clay',
           'Miami': 'hard',
           'Indian Wells': 'hard',
           'Dubai': 'hard',
           'Paris': 'hard',
           'Stuttgart': 'grass',
           'Rotterdam': 'hard',
           'Canada': 'hard',
           'Monte Carlo': 'clay',
           'Brisbane': 'hard',
           'Istanbul': 'hard',
           'Davis Cup': 'hard',
           'Hamburg': 'clay',
           'London Olympics': 'grass',
           'Stockholm': 'hard',
           'Masters Cup': 'hard',
           'Beijing Olympics': 'hard',
           'Estoril': 'clay',
           'Tokyo': 'hard',
           'Bangkok': 'hard',
           'Gstaad': 'clay',
           'Vienna': 'hard',
           'Munich': 'clay',
           'Marseille': 'hard',
           'Milan': 'clay',
           'Sydney': 'hard',
           'Sydney Olympics': 'hard',
           's Hertogenbosch': 'grass',
           'Buenos Aires': 'clay',
           'Barcelona': 'clay',
           "Queen's Club": 'grass',
           'Rio de Janeiro': 'clay',
           'Atp Cup': 'hard',
           'Antwerp': 'hard',
           'Cologne 2': 'hard',
           'Cordoba': 'clay',
           'Los Cabos': 'hard',
           'Acapulco': 'hard',
           'Marrakech': 'clay',
           'Sao Paulo': 'clay',
           'Montevideo CH': 'clay',
           'Guayaquil CH': 'clay',
           'Corrientes CH': 'clay',
           'Potro Alegre CH': 'clay',
           'Campinas CH': 'clay',
           'Bastad': 'clay'}
man['surface'] = man['tourney'].apply(lambda x: surfaces[x])
man.head()

,year,tourney,round,result,opponent,overall: Unret%,overall: <=3 W%,overall: RiP W%,overall: SvImpact,1st: Unret%,...,1st: RiP W%,1st: SvImpact,1st: D Wide%,1st: A Wide%,1st: A BP Wide%,2nd: Unret%,2nd: <=3 W%,2nd: RiP W%,2ndAgg,surface
0,2025,Buenos Aires,R16,L,Martinez,9.5,19.0,38.2,16.0,14.8,...,34.8,24.8,22.2,38.9,20.0,0.0,9.1,45.5,-118,clay
1,2025,Buenos Aires,R32,W,Jarry,26.3,35.1,57.5,31.4,27.6,...,58.2,35.3,31.3,47.7,33.3,26.5,32.4,56.0,80,clay
2,2024,US Open,R128,L,Monfils,11.3,17.4,47.0,15.0,16.2,...,43.5,21.9,54.3,43.6,33.3,2.6,5.1,52.6,-91,hard
3,2023,Wimbledon,R64,L,Sinner,13.6,17.3,47.1,17.7,15.5,...,51.0,21.2,53.8,15.6,16.7,9.5,9.5,36.8,-22,grass
4,2023,Barcelona,R64,W,Wu,23.8,31.0,59.4,27.9,25.0,...,47.6,31.1,60.0,30.8,NaN,21.4,35.7,81.8,-79,clay

In [28]:
man = pd.get_dummies(man, columns=['surface', 'result'])
man.drop(columns=['result_L'], inplace=True)
#columns after one hot encoding
man.columns

Index(['year', 'tourney', 'round', 'opponent', 'overall: Unret%',
       'overall: <=3 W%', 'overall: RiP W%', 'overall: SvImpact',
       '1st: Unret%', '1st: <=3 W%', '1st: RiP W%', '1st: SvImpact',
       '1st: D Wide%', '1st: A Wide%', '1st: A BP Wide%', '2nd: Unret%',
       '2nd: <=3 W%', '2nd: RiP W%', '2ndAgg', 'surface_clay', 'surface_grass',
       'surface_hard', 'result_W'],
      dtype='object')

In [29]:
man.to_csv('../data/schwartzman_serve_chart.csv', index=False)

In [30]:
man.isna().sum() #show the number of missing values in each column

year                 0
tourney              0
round                0
opponent             0
overall: Unret%      0
overall: <=3 W%      0
overall: RiP W%      0
overall: SvImpact    0
1st: Unret%          0
1st: <=3 W%          0
1st: RiP W%          0
1st: SvImpact        0
1st: D Wide%         0
1st: A Wide%         0
1st: A BP Wide%      7
2nd: Unret%          0
2nd: <=3 W%          0
2nd: RiP W%          0
2ndAgg               0
surface_clay         0
surface_grass        0
surface_hard         0
result_W             0
dtype: int64

In [31]:
#use simple imputation to fill in missing values with the column mean
man_imputed = man.copy()
man_imputed['1st: A BP Wide%'].fillna(man_imputed['1st: A BP Wide%'].mean(), inplace=True)
man_imputed.isna().sum() #show the number of missing values in each column after imputation

year                 0
tourney              0
round                0
opponent             0
overall: Unret%      0
overall: <=3 W%      0
overall: RiP W%      0
overall: SvImpact    0
1st: Unret%          0
1st: <=3 W%          0
1st: RiP W%          0
1st: SvImpact        0
1st: D Wide%         0
1st: A Wide%         0
1st: A BP Wide%      0
2nd: Unret%          0
2nd: <=3 W%          0
2nd: RiP W%          0
2ndAgg               0
surface_clay         0
surface_grass        0
surface_hard         0
result_W             0
dtype: int64

In [ ]:
#save the imputed data
man_imputed.to_csv('../data/schwartzman_serve_chart_imputed.csv', index=False)

In [32]:
man_speed = pd.read_csv('../data/schwartzman_serve_speed.csv')
man_speed.head()

,year,tourney,round,result,opponent,avg speed,1st: avg,1st: stdev,1st: t avg,1st: wide avg,1st: max,1st: min,2nd: avg,2nd: stdev,2nd: t avg,2nd: wide avg,2nd: max,2nd: min
0,2024,US Open,R128,L,Monfils,94.9,100.4,4.8,103.5,97.4,114.0,92.0,84.8,4.8,87.6,80.3,95.0,76.0
1,2023,US Open,R128,L,Rinderknech,94.2,100.2,4.8,103.8,97.3,114.0,90.0,82.6,3.7,79.3,NaN,89.0,75.0
2,2023,Wimbledon,R64,L,Sinner,97.2,102.7,5.1,107.6,99.5,115.0,92.0,82.2,3.6,84.5,NaN,88.0,73.0
3,2022,US Open,R32,L,Tiafoe,96.6,101.1,5.9,103.6,98.9,115.0,88.0,85.3,5.6,81.5,83.0,96.0,72.0
4,2022,US Open,R64,W,Popyrin,94.9,98.8,5.2,102.6,97.1,111.0,87.0,85.8,5.0,80.5,82.7,94.0,72.0

In [33]:
#one hot encoding for surface and result
man_speed['surface'] = man_speed['tourney'].apply(lambda x: surfaces[x])
man_speed = pd.get_dummies(man_speed, columns=['surface', 'result'])
man_speed.drop(columns=['result_L'], inplace=True)
man_speed.head()

,year,tourney,round,opponent,avg speed,1st: avg,1st: stdev,1st: t avg,1st: wide avg,1st: max,...,2nd: avg,2nd: stdev,2nd: t avg,2nd: wide avg,2nd: max,2nd: min,surface_clay,surface_grass,surface_hard,result_W
0,2024,US Open,R128,Monfils,94.9,100.4,4.8,103.5,97.4,114.0,...,84.8,4.8,87.6,80.3,95.0,76.0,False,False,True,False
1,2023,US Open,R128,Rinderknech,94.2,100.2,4.8,103.8,97.3,114.0,...,82.6,3.7,79.3,NaN,89.0,75.0,False,False,True,False
2,2023,Wimbledon,R64,Sinner,97.2,102.7,5.1,107.6,99.5,115.0,...,82.2,3.6,84.5,NaN,88.0,73.0,False,True,False,False
3,2022,US Open,R32,Tiafoe,96.6,101.1,5.9,103.6,98.9,115.0,...,85.3,5.6,81.5,83.0,96.0,72.0,False,False,True,False
4,2022,US Open,R64,Popyrin,94.9,98.8,5.2,102.6,97.1,111.0,...,85.8,5.0,80.5,82.7,94.0,72.0,False,False,True,True

In [34]:
# save the data
man_speed.to_csv('../data/schwartzman_serve_speed.csv', index=False)

In [35]:
man_speed.isna().sum() #show the number of missing values in each column

year              0
tourney           0
round             0
opponent          0
avg speed         0
1st: avg          0
1st: stdev        0
1st: t avg        8
1st: wide avg     8
1st: max          0
1st: min          0
2nd: avg          0
2nd: stdev        0
2nd: t avg        8
2nd: wide avg    15
2nd: max          0
2nd: min          0
surface_clay      0
surface_grass     0
surface_hard      0
result_W          0
dtype: int64

In [36]:
# use simple imputation to fill in missing values with the column mean
man_speed_imputed = man_speed.copy()
cols_to_impute = ['1st: avg','1st: stdev','1st: t avg','1st: wide avg','1st: max','1st: min','2nd: avg','2nd: stdev',
                  '2nd: t avg','2nd: wide avg','2nd: max']
for col in cols_to_impute:
    man_speed_imputed[col].fillna(man_speed_imputed[col].mean(), inplace=True)
man_speed_imputed.isna().sum() #show the number of missing values in each column after imputation

year             0
tourney          0
round            0
opponent         0
avg speed        0
1st: avg         0
1st: stdev       0
1st: t avg       0
1st: wide avg    0
1st: max         0
1st: min         0
2nd: avg         0
2nd: stdev       0
2nd: t avg       0
2nd: wide avg    0
2nd: max         0
2nd: min         0
surface_clay     0
surface_grass    0
surface_hard     0
result_W         0
dtype: int64

In [37]:
#save the imputed data
man_speed_imputed.to_csv('../data/schwartzman_serve_speed_imputed.csv', index=False)